schema: "classroom50/repo-config/v1"
classroom: "swdevprac2-69-1"
assignment: "a08-swdevprac2-69-1"
secret: "cf2djm54"
owner:
  username: "cholanuchkorn123"
  id: 111271006
  accepted_at: "2026-10-06T16:10:59Z"
source:
  owner: "SWDevPrac2-69-1"
  owner_id: 312147402
  repo: "2110507_a08_starter"
  branch: "main"
